[general]
bars = 12
sleep_timer = 5

[input]

[output]
method = raw

raw_target = /dev/stdout
data_format = ascii
bar_delimiter = 0

; for glsl output mode, keep rendering even if no audio

[color]

[smoothing]

[eq]
