[main]
# Font
font=MD IO Trial Medium:size=12, Maple Mono NF CN:size=12, Noto Color Emoji:size=12

# UI
pad=10x10
bold-text-in-bright=palette-based
include=/home/loki/.config/foot/themes/catppuccin.ini

# Performance
[tweak]
font-monospace-warn=false
