#! /bin/sh

# Launch sxhkd
sxhkd &

# Launch redshift with coordinates for Pune
redshift &

# Launch polybar
polybar nord &

bspc monitor -d I II III IV V VI VII

bspc config border_width         4
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle	 false

bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"

bspc rule -a Zathura state=tiled
bspc rule -a Pinentry-gtk-2 state=floating
bspc rule -a feh state=fullscreen
