#! /bin/sh

# Launch sxhkd
sxhkd &

# Launch redshift with coordinates for Kolhapur
redshift &

# Launch polybar
polybar nord &

# Desktops
bspc monitor -d I II III IV V VI VII VIII IX X

# Border and Gap
bspc config border_width         2
bspc config window_gap          10

# Configuration
bspc config split_ratio          0.50

# Mouse
bspc config click_to_focus	 button1

# Monocle mode settings
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle	 true

# Colors
bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"

# Rules
bspc rule -a Zathura desktop='^3' state=tiled
bspc rule -a Nightly desktop='^2' state=tiled
bspc rule -a Pinentry-gtk-2 state=floating
bspc rule -a feh state=fullscreen

# Rules for Firefox windows
bspc rule -a Nightly:Browser state=floating
bspc rule -a Nightly:Dialog state=floating
bspc rule -a Nightly:firefox state=floating
bspc rule -a Nightly:Prompt state=floating
